import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";

interface RepositoryConfigFormProps {
  repoUrl: string;
  setRepoUrl: (url: string) => void;
  autoCreatePR: boolean;
  setAutoCreatePR: (value: boolean) => void;
  autoGenerateDocs: boolean;
  setAutoGenerateDocs: (value: boolean) => void;
  autoAnalyzeIssues: boolean;
  setAutoAnalyzeIssues: (value: boolean) => void;
}

export function RepositoryConfigForm({
  repoUrl,
  setRepoUrl,
  autoCreatePR,
  setAutoCreatePR,
  autoGenerateDocs,
  setAutoGenerateDocs,
  autoAnalyzeIssues,
  setAutoAnalyzeIssues,
}: RepositoryConfigFormProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Repository Configuration</CardTitle>
        <CardDescription>
          Configure how the LLM interacts with your repositories
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="repo-url">Default Repository URL</Label>
          <Input
            id="repo-url"
            value={repoUrl}
            onChange={(e) => setRepoUrl(e.target.value)}
            placeholder="https://github.com/username/repository"
          />
        </div>

        <div className="space-y-4 pt-4">
          <h3 className="text-lg font-medium">Automation Settings</h3>

          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label htmlFor="auto-pr">
                Automatically Create Pull Requests
              </Label>
              <p className="text-sm text-muted-foreground">
                Allow the LLM to create branches and PRs for fixes
              </p>
            </div>
            <Switch
              id="auto-pr"
              checked={autoCreatePR}
              onCheckedChange={setAutoCreatePR}
            />
          </div>

          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label htmlFor="auto-docs">
                Automatically Generate Documentation
              </Label>
              <p className="text-sm text-muted-foreground">
                Allow the LLM to create and update documentation files
              </p>
            </div>
            <Switch
              id="auto-docs"
              checked={autoGenerateDocs}
              onCheckedChange={setAutoGenerateDocs}
            />
          </div>

          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label htmlFor="auto-issues">
                Automatically Analyze Issues
              </Label>
              <p className="text-sm text-muted-foreground">
                Allow the LLM to analyze and work on open issues
              </p>
            </div>
            <Switch
              id="auto-issues"
              checked={autoAnalyzeIssues}
              onCheckedChange={setAutoAnalyzeIssues}
            />
          </div>
        </div>
      </CardContent>
      <CardFooter>
        <Button>Save Settings</Button>
      </CardFooter>
    </Card>
  );
}