import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { RepositoryUrlField } from "./repository-url-field";
import { AutomationSwitch } from "./automation-switch";
import { useRepositoryAutomation, UseRepositoryAutomationProps } from "../hooks/use-repository-automation";

/**
 * Props for RepositoryConfigForm component.
 */
export interface RepositoryConfigFormProps extends UseRepositoryAutomationProps {
  /** The current repository URL value */
  repoUrl: string;
  /** Callback to update the repository URL */
  setRepoUrl: (url: string) => void;
}

/**
 * RepositoryConfigForm orchestrates repository configuration UI.
 */
export function RepositoryConfigForm({
  repoUrl,
  setRepoUrl,
  autoCreatePR,
  setAutoCreatePR,
  autoGenerateDocs,
  setAutoGenerateDocs,
  autoAnalyzeIssues,
  setAutoAnalyzeIssues,
}: RepositoryConfigFormProps) {
  const {
    autoCreatePR: pr,
    handleAutoCreatePR,
    autoGenerateDocs: docs,
    handleAutoGenerateDocs,
    autoAnalyzeIssues: issues,
    handleAutoAnalyzeIssues,
  } = useRepositoryAutomation({
    autoCreatePR,
    setAutoCreatePR,
    autoGenerateDocs,
    setAutoGenerateDocs,
    autoAnalyzeIssues,
    setAutoAnalyzeIssues,
  });

  return (
    <Card>
      <CardHeader>
        <CardTitle>Repository Configuration</CardTitle>
        <CardDescription>
          Configure how the LLM interacts with your repositories
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <RepositoryUrlField value={repoUrl} onChange={setRepoUrl} />
        <div className="space-y-4 pt-4">
          <h3 className="text-lg font-medium">Automation Settings</h3>
          <AutomationSwitch
            id="auto-pr"
            label="Automatically Create Pull Requests"
            description="Allow the LLM to create branches and PRs for fixes"
            checked={pr}
            onCheckedChange={handleAutoCreatePR}
          />
          <AutomationSwitch
            id="auto-docs"
            label="Automatically Generate Documentation"
            description="Allow the LLM to create and update documentation files"
            checked={docs}
            onCheckedChange={handleAutoGenerateDocs}
          />
          <AutomationSwitch
            id="auto-issues"
            label="Automatically Analyze Issues"
            description="Allow the LLM to analyze and work on open issues"
            checked={issues}
            onCheckedChange={handleAutoAnalyzeIssues}
          />
        </div>
      </CardContent>
      <CardFooter>
        <Button>Save Settings</Button>
      </CardFooter>
    </Card>
  );
}