import { useCallback } from "react";

/**
 * Props for useRepositoryAutomation hook.
 */
export interface UseRepositoryAutomationProps {
  autoCreatePR: boolean;
  setAutoCreatePR: (value: boolean) => void;
  autoGenerateDocs: boolean;
  setAutoGenerateDocs: (value: boolean) => void;
  autoAnalyzeIssues: boolean;
  setAutoAnalyzeIssues: (value: boolean) => void;
}

/**
 * Centralizes automation switches state and handlers for repository config.
 */
export function useRepositoryAutomation({
  autoCreatePR,
  setAutoCreatePR,
  autoGenerateDocs,
  setAutoGenerateDocs,
  autoAnalyzeIssues,
  setAutoAnalyzeIssues,
}: UseRepositoryAutomationProps) {
  // Optionally, memoize handlers if needed
  const handleAutoCreatePR = useCallback(setAutoCreatePR, [setAutoCreatePR]);
  const handleAutoGenerateDocs = useCallback(setAutoGenerateDocs, [setAutoGenerateDocs]);
  const handleAutoAnalyzeIssues = useCallback(setAutoAnalyzeIssues, [setAutoAnalyzeIssues]);

  return {
    autoCreatePR,
    handleAutoCreatePR,
    autoGenerateDocs,
    handleAutoGenerateDocs,
    autoAnalyzeIssues,
    handleAutoAnalyzeIssues,
  };
}