// src/core/ports/services/embedding.interface.ts

// Note: EmbeddingResult might be imported if generateEmbedding returned Promise<EmbeddingResult>
// import { EmbeddingResult } from '../../domain/ai/embedding.types';

export interface IEmbeddingService {
  /**
   * Generates an embedding vector for the given text.
   * @param text The text to generate an embedding for.
   * @returns A promise that resolves to an array of numbers representing the embedding.
   */
  generateEmbedding(text: string): Promise<number[]>;

  /**
   * The dimensionality of the embeddings generated by this service.
   */
  readonly dimensions: number;
}
