/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as publicOnboardingIndexRouteImport } from './app/(public)/onboarding/index'
import { Route as appSettingsIndexRouteImport } from './app/(app)/settings/index'
import { Route as appProjectsIndexRouteImport } from './app/(app)/projects/index'
import { Route as appPersonasIndexRouteImport } from './app/(app)/personas/index'
import { Route as appDashboardIndexRouteImport } from './app/(app)/dashboard/index'
import { Route as appChatIndexRouteImport } from './app/(app)/chat/index'
import { Route as appAgentsIndexRouteImport } from './app/(app)/agents/index'
import { Route as appSettingsProfileIndexRouteImport } from './app/(app)/settings/profile/index'
import { Route as appSettingsLlmIndexRouteImport } from './app/(app)/settings/llm/index'
import { Route as appSettingsAppearanceIndexRouteImport } from './app/(app)/settings/appearance/index'
import { Route as appProjectsNewIndexRouteImport } from './app/(app)/projects/new/index'
import { Route as appProjectsProjectIdIndexRouteImport } from './app/(app)/projects/$projectId/index'
import { Route as appPersonasNewIndexRouteImport } from './app/(app)/personas/new/index'
import { Route as appPersonasTemplateIdIndexRouteImport } from './app/(app)/personas/$templateId/index'
import { Route as appAgentsNewIndexRouteImport } from './app/(app)/agents/new/index'
import { Route as appAgentsAgentIdIndexRouteImport } from './app/(app)/agents/$agentId/index'
import { Route as appSettingsLlmNewIndexRouteImport } from './app/(app)/settings/llm/new/index'
import { Route as appProjectsProjectIdSettingsIndexRouteImport } from './app/(app)/projects/$projectId/settings/index'
import { Route as appProjectsProjectIdMembersIndexRouteImport } from './app/(app)/projects/$projectId/members/index'
import { Route as appProjectsProjectIdDocsIndexRouteImport } from './app/(app)/projects/$projectId/docs/index'
import { Route as appProjectsProjectIdChatIndexRouteImport } from './app/(app)/projects/$projectId/chat/index'
import { Route as appPersonasTemplateIdEditIndexRouteImport } from './app/(app)/personas/$templateId/edit/index'
import { Route as appAgentsAgentIdEditIndexRouteImport } from './app/(app)/agents/$agentId/edit/index'
import { Route as appSettingsLlmConfigIdEditIndexRouteImport } from './app/(app)/settings/llm/$configId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOnboardingIndexRoute = publicOnboardingIndexRouteImport.update({
  id: '/(public)/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/(app)/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const appProjectsIndexRoute = appProjectsIndexRouteImport.update({
  id: '/(app)/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const appPersonasIndexRoute = appPersonasIndexRouteImport.update({
  id: '/(app)/personas/',
  path: '/personas/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/(app)/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const appChatIndexRoute = appChatIndexRouteImport.update({
  id: '/(app)/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAgentsIndexRoute = appAgentsIndexRouteImport.update({
  id: '/(app)/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsProfileIndexRoute = appSettingsProfileIndexRouteImport.update({
  id: '/(app)/settings/profile/',
  path: '/settings/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsLlmIndexRoute = appSettingsLlmIndexRouteImport.update({
  id: '/(app)/settings/llm/',
  path: '/settings/llm/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsAppearanceIndexRoute =
  appSettingsAppearanceIndexRouteImport.update({
    id: '/(app)/settings/appearance/',
    path: '/settings/appearance/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appProjectsNewIndexRoute = appProjectsNewIndexRouteImport.update({
  id: '/(app)/projects/new/',
  path: '/projects/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const appProjectsProjectIdIndexRoute =
  appProjectsProjectIdIndexRouteImport.update({
    id: '/(app)/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appPersonasNewIndexRoute = appPersonasNewIndexRouteImport.update({
  id: '/(app)/personas/new/',
  path: '/personas/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const appPersonasTemplateIdIndexRoute =
  appPersonasTemplateIdIndexRouteImport.update({
    id: '/(app)/personas/$templateId/',
    path: '/personas/$templateId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appAgentsNewIndexRoute = appAgentsNewIndexRouteImport.update({
  id: '/(app)/agents/new/',
  path: '/agents/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAgentsAgentIdIndexRoute = appAgentsAgentIdIndexRouteImport.update({
  id: '/(app)/agents/$agentId/',
  path: '/agents/$agentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsLlmNewIndexRoute = appSettingsLlmNewIndexRouteImport.update({
  id: '/(app)/settings/llm/new/',
  path: '/settings/llm/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const appProjectsProjectIdSettingsIndexRoute =
  appProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/(app)/projects/$projectId/settings/',
    path: '/projects/$projectId/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appProjectsProjectIdMembersIndexRoute =
  appProjectsProjectIdMembersIndexRouteImport.update({
    id: '/(app)/projects/$projectId/members/',
    path: '/projects/$projectId/members/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appProjectsProjectIdDocsIndexRoute =
  appProjectsProjectIdDocsIndexRouteImport.update({
    id: '/(app)/projects/$projectId/docs/',
    path: '/projects/$projectId/docs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appProjectsProjectIdChatIndexRoute =
  appProjectsProjectIdChatIndexRouteImport.update({
    id: '/(app)/projects/$projectId/chat/',
    path: '/projects/$projectId/chat/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appPersonasTemplateIdEditIndexRoute =
  appPersonasTemplateIdEditIndexRouteImport.update({
    id: '/(app)/personas/$templateId/edit/',
    path: '/personas/$templateId/edit/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appAgentsAgentIdEditIndexRoute =
  appAgentsAgentIdEditIndexRouteImport.update({
    id: '/(app)/agents/$agentId/edit/',
    path: '/agents/$agentId/edit/',
    getParentRoute: () => rootRouteImport,
  } as any)
const appSettingsLlmConfigIdEditIndexRoute =
  appSettingsLlmConfigIdEditIndexRouteImport.update({
    id: '/(app)/settings/llm/$configId/edit/',
    path: '/settings/llm/$configId/edit/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof appAgentsIndexRoute
  '/chat': typeof appChatIndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/personas': typeof appPersonasIndexRoute
  '/projects': typeof appProjectsIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/onboarding': typeof publicOnboardingIndexRoute
  '/agents/$agentId': typeof appAgentsAgentIdIndexRoute
  '/agents/new': typeof appAgentsNewIndexRoute
  '/personas/$templateId': typeof appPersonasTemplateIdIndexRoute
  '/personas/new': typeof appPersonasNewIndexRoute
  '/projects/$projectId': typeof appProjectsProjectIdIndexRoute
  '/projects/new': typeof appProjectsNewIndexRoute
  '/settings/appearance': typeof appSettingsAppearanceIndexRoute
  '/settings/llm': typeof appSettingsLlmIndexRoute
  '/settings/profile': typeof appSettingsProfileIndexRoute
  '/agents/$agentId/edit': typeof appAgentsAgentIdEditIndexRoute
  '/personas/$templateId/edit': typeof appPersonasTemplateIdEditIndexRoute
  '/projects/$projectId/chat': typeof appProjectsProjectIdChatIndexRoute
  '/projects/$projectId/docs': typeof appProjectsProjectIdDocsIndexRoute
  '/projects/$projectId/members': typeof appProjectsProjectIdMembersIndexRoute
  '/projects/$projectId/settings': typeof appProjectsProjectIdSettingsIndexRoute
  '/settings/llm/new': typeof appSettingsLlmNewIndexRoute
  '/settings/llm/$configId/edit': typeof appSettingsLlmConfigIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof appAgentsIndexRoute
  '/chat': typeof appChatIndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/personas': typeof appPersonasIndexRoute
  '/projects': typeof appProjectsIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/onboarding': typeof publicOnboardingIndexRoute
  '/agents/$agentId': typeof appAgentsAgentIdIndexRoute
  '/agents/new': typeof appAgentsNewIndexRoute
  '/personas/$templateId': typeof appPersonasTemplateIdIndexRoute
  '/personas/new': typeof appPersonasNewIndexRoute
  '/projects/$projectId': typeof appProjectsProjectIdIndexRoute
  '/projects/new': typeof appProjectsNewIndexRoute
  '/settings/appearance': typeof appSettingsAppearanceIndexRoute
  '/settings/llm': typeof appSettingsLlmIndexRoute
  '/settings/profile': typeof appSettingsProfileIndexRoute
  '/agents/$agentId/edit': typeof appAgentsAgentIdEditIndexRoute
  '/personas/$templateId/edit': typeof appPersonasTemplateIdEditIndexRoute
  '/projects/$projectId/chat': typeof appProjectsProjectIdChatIndexRoute
  '/projects/$projectId/docs': typeof appProjectsProjectIdDocsIndexRoute
  '/projects/$projectId/members': typeof appProjectsProjectIdMembersIndexRoute
  '/projects/$projectId/settings': typeof appProjectsProjectIdSettingsIndexRoute
  '/settings/llm/new': typeof appSettingsLlmNewIndexRoute
  '/settings/llm/$configId/edit': typeof appSettingsLlmConfigIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/agents/': typeof appAgentsIndexRoute
  '/(app)/chat/': typeof appChatIndexRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/personas/': typeof appPersonasIndexRoute
  '/(app)/projects/': typeof appProjectsIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(public)/onboarding/': typeof publicOnboardingIndexRoute
  '/(app)/agents/$agentId/': typeof appAgentsAgentIdIndexRoute
  '/(app)/agents/new/': typeof appAgentsNewIndexRoute
  '/(app)/personas/$templateId/': typeof appPersonasTemplateIdIndexRoute
  '/(app)/personas/new/': typeof appPersonasNewIndexRoute
  '/(app)/projects/$projectId/': typeof appProjectsProjectIdIndexRoute
  '/(app)/projects/new/': typeof appProjectsNewIndexRoute
  '/(app)/settings/appearance/': typeof appSettingsAppearanceIndexRoute
  '/(app)/settings/llm/': typeof appSettingsLlmIndexRoute
  '/(app)/settings/profile/': typeof appSettingsProfileIndexRoute
  '/(app)/agents/$agentId/edit/': typeof appAgentsAgentIdEditIndexRoute
  '/(app)/personas/$templateId/edit/': typeof appPersonasTemplateIdEditIndexRoute
  '/(app)/projects/$projectId/chat/': typeof appProjectsProjectIdChatIndexRoute
  '/(app)/projects/$projectId/docs/': typeof appProjectsProjectIdDocsIndexRoute
  '/(app)/projects/$projectId/members/': typeof appProjectsProjectIdMembersIndexRoute
  '/(app)/projects/$projectId/settings/': typeof appProjectsProjectIdSettingsIndexRoute
  '/(app)/settings/llm/new/': typeof appSettingsLlmNewIndexRoute
  '/(app)/settings/llm/$configId/edit/': typeof appSettingsLlmConfigIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/chat'
    | '/dashboard'
    | '/personas'
    | '/projects'
    | '/settings'
    | '/onboarding'
    | '/agents/$agentId'
    | '/agents/new'
    | '/personas/$templateId'
    | '/personas/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/appearance'
    | '/settings/llm'
    | '/settings/profile'
    | '/agents/$agentId/edit'
    | '/personas/$templateId/edit'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/docs'
    | '/projects/$projectId/members'
    | '/projects/$projectId/settings'
    | '/settings/llm/new'
    | '/settings/llm/$configId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/chat'
    | '/dashboard'
    | '/personas'
    | '/projects'
    | '/settings'
    | '/onboarding'
    | '/agents/$agentId'
    | '/agents/new'
    | '/personas/$templateId'
    | '/personas/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/appearance'
    | '/settings/llm'
    | '/settings/profile'
    | '/agents/$agentId/edit'
    | '/personas/$templateId/edit'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/docs'
    | '/projects/$projectId/members'
    | '/projects/$projectId/settings'
    | '/settings/llm/new'
    | '/settings/llm/$configId/edit'
  id:
    | '__root__'
    | '/'
    | '/(app)/agents/'
    | '/(app)/chat/'
    | '/(app)/dashboard/'
    | '/(app)/personas/'
    | '/(app)/projects/'
    | '/(app)/settings/'
    | '/(public)/onboarding/'
    | '/(app)/agents/$agentId/'
    | '/(app)/agents/new/'
    | '/(app)/personas/$templateId/'
    | '/(app)/personas/new/'
    | '/(app)/projects/$projectId/'
    | '/(app)/projects/new/'
    | '/(app)/settings/appearance/'
    | '/(app)/settings/llm/'
    | '/(app)/settings/profile/'
    | '/(app)/agents/$agentId/edit/'
    | '/(app)/personas/$templateId/edit/'
    | '/(app)/projects/$projectId/chat/'
    | '/(app)/projects/$projectId/docs/'
    | '/(app)/projects/$projectId/members/'
    | '/(app)/projects/$projectId/settings/'
    | '/(app)/settings/llm/new/'
    | '/(app)/settings/llm/$configId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAgentsIndexRoute: typeof appAgentsIndexRoute
  appChatIndexRoute: typeof appChatIndexRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appPersonasIndexRoute: typeof appPersonasIndexRoute
  appProjectsIndexRoute: typeof appProjectsIndexRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
  publicOnboardingIndexRoute: typeof publicOnboardingIndexRoute
  appAgentsAgentIdIndexRoute: typeof appAgentsAgentIdIndexRoute
  appAgentsNewIndexRoute: typeof appAgentsNewIndexRoute
  appPersonasTemplateIdIndexRoute: typeof appPersonasTemplateIdIndexRoute
  appPersonasNewIndexRoute: typeof appPersonasNewIndexRoute
  appProjectsProjectIdIndexRoute: typeof appProjectsProjectIdIndexRoute
  appProjectsNewIndexRoute: typeof appProjectsNewIndexRoute
  appSettingsAppearanceIndexRoute: typeof appSettingsAppearanceIndexRoute
  appSettingsLlmIndexRoute: typeof appSettingsLlmIndexRoute
  appSettingsProfileIndexRoute: typeof appSettingsProfileIndexRoute
  appAgentsAgentIdEditIndexRoute: typeof appAgentsAgentIdEditIndexRoute
  appPersonasTemplateIdEditIndexRoute: typeof appPersonasTemplateIdEditIndexRoute
  appProjectsProjectIdChatIndexRoute: typeof appProjectsProjectIdChatIndexRoute
  appProjectsProjectIdDocsIndexRoute: typeof appProjectsProjectIdDocsIndexRoute
  appProjectsProjectIdMembersIndexRoute: typeof appProjectsProjectIdMembersIndexRoute
  appProjectsProjectIdSettingsIndexRoute: typeof appProjectsProjectIdSettingsIndexRoute
  appSettingsLlmNewIndexRoute: typeof appSettingsLlmNewIndexRoute
  appSettingsLlmConfigIdEditIndexRoute: typeof appSettingsLlmConfigIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/onboarding/': {
      id: '/(public)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof publicOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/projects/': {
      id: '/(app)/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof appProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/personas/': {
      id: '/(app)/personas/'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof appPersonasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/chat/': {
      id: '/(app)/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/agents/': {
      id: '/(app)/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof appAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/profile/': {
      id: '/(app)/settings/profile/'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof appSettingsProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/llm/': {
      id: '/(app)/settings/llm/'
      path: '/settings/llm'
      fullPath: '/settings/llm'
      preLoaderRoute: typeof appSettingsLlmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/appearance/': {
      id: '/(app)/settings/appearance/'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof appSettingsAppearanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/projects/new/': {
      id: '/(app)/projects/new/'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof appProjectsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/projects/$projectId/': {
      id: '/(app)/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof appProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/personas/new/': {
      id: '/(app)/personas/new/'
      path: '/personas/new'
      fullPath: '/personas/new'
      preLoaderRoute: typeof appPersonasNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/personas/$templateId/': {
      id: '/(app)/personas/$templateId/'
      path: '/personas/$templateId'
      fullPath: '/personas/$templateId'
      preLoaderRoute: typeof appPersonasTemplateIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/agents/new/': {
      id: '/(app)/agents/new/'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof appAgentsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/agents/$agentId/': {
      id: '/(app)/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof appAgentsAgentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/llm/new/': {
      id: '/(app)/settings/llm/new/'
      path: '/settings/llm/new'
      fullPath: '/settings/llm/new'
      preLoaderRoute: typeof appSettingsLlmNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/projects/$projectId/settings/': {
      id: '/(app)/projects/$projectId/settings/'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof appProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/projects/$projectId/members/': {
      id: '/(app)/projects/$projectId/members/'
      path: '/projects/$projectId/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof appProjectsProjectIdMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/projects/$projectId/docs/': {
      id: '/(app)/projects/$projectId/docs/'
      path: '/projects/$projectId/docs'
      fullPath: '/projects/$projectId/docs'
      preLoaderRoute: typeof appProjectsProjectIdDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/projects/$projectId/chat/': {
      id: '/(app)/projects/$projectId/chat/'
      path: '/projects/$projectId/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof appProjectsProjectIdChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/personas/$templateId/edit/': {
      id: '/(app)/personas/$templateId/edit/'
      path: '/personas/$templateId/edit'
      fullPath: '/personas/$templateId/edit'
      preLoaderRoute: typeof appPersonasTemplateIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/agents/$agentId/edit/': {
      id: '/(app)/agents/$agentId/edit/'
      path: '/agents/$agentId/edit'
      fullPath: '/agents/$agentId/edit'
      preLoaderRoute: typeof appAgentsAgentIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings/llm/$configId/edit/': {
      id: '/(app)/settings/llm/$configId/edit/'
      path: '/settings/llm/$configId/edit'
      fullPath: '/settings/llm/$configId/edit'
      preLoaderRoute: typeof appSettingsLlmConfigIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAgentsIndexRoute: appAgentsIndexRoute,
  appChatIndexRoute: appChatIndexRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
  appPersonasIndexRoute: appPersonasIndexRoute,
  appProjectsIndexRoute: appProjectsIndexRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
  publicOnboardingIndexRoute: publicOnboardingIndexRoute,
  appAgentsAgentIdIndexRoute: appAgentsAgentIdIndexRoute,
  appAgentsNewIndexRoute: appAgentsNewIndexRoute,
  appPersonasTemplateIdIndexRoute: appPersonasTemplateIdIndexRoute,
  appPersonasNewIndexRoute: appPersonasNewIndexRoute,
  appProjectsProjectIdIndexRoute: appProjectsProjectIdIndexRoute,
  appProjectsNewIndexRoute: appProjectsNewIndexRoute,
  appSettingsAppearanceIndexRoute: appSettingsAppearanceIndexRoute,
  appSettingsLlmIndexRoute: appSettingsLlmIndexRoute,
  appSettingsProfileIndexRoute: appSettingsProfileIndexRoute,
  appAgentsAgentIdEditIndexRoute: appAgentsAgentIdEditIndexRoute,
  appPersonasTemplateIdEditIndexRoute: appPersonasTemplateIdEditIndexRoute,
  appProjectsProjectIdChatIndexRoute: appProjectsProjectIdChatIndexRoute,
  appProjectsProjectIdDocsIndexRoute: appProjectsProjectIdDocsIndexRoute,
  appProjectsProjectIdMembersIndexRoute: appProjectsProjectIdMembersIndexRoute,
  appProjectsProjectIdSettingsIndexRoute:
    appProjectsProjectIdSettingsIndexRoute,
  appSettingsLlmNewIndexRoute: appSettingsLlmNewIndexRoute,
  appSettingsLlmConfigIdEditIndexRoute: appSettingsLlmConfigIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
