services:
  # frontend:
  #   build: ./frontend
  #   networks:
  #     - projectwiz
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - PORT=3001
  #     - CHROMA_CLIENT_AUTH_CREDENTIALS=${CHROMA_CLIENT_AUTH_CREDENTIALS}
  
  # backend:
  #   build: ./backend
  #   networks:
  #     - projectwiz
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CHROMA_CLIENT_AUTH_CREDENTIALS=${CHROMA_CLIENT_AUTH_CREDENTIALS}
  
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    networks:
      - projectwiz
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    volumes:
      - redis-data:/data
      # - /local-redis-stack.conf:/redis-stack.conf

  chromadb:
    image: chromadb/chroma
    networks:
      - projectwiz
    environment:
      - CHROMA_SERVER_AUTHN_CREDENTIALS=${CHROMA_CLIENT_AUTH_CREDENTIALS}
      - CHROMA_SERVER_AUTHN_PROVIDER=${CHROMA_SERVER_AUTHN_PROVIDER}
    ports:
      - 8000:8000
    volumes:
      # - ./chromadb/.chroma_env:.chroma_env
      - chromadb-data:/chroma/chroma
  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      - projectwiz
    ports:
      - "3100:3100"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki/runtime_config.yaml:/etc/loki/runtime_config.yaml
    command: -config.file=/etc/loki/local-config.yaml -config.expand-env=true
    depends_on:
      - minio

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"
    networks:
      - projectwiz
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - projectwiz
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
      - ./minio/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

networks:
  projectwiz:

volumes:
  redis-data:
  chromadb-data:
  minio-data:
  grafana-data:
