#!/bin/bash
# This script was generated by Gemini to help you automate fixing errors.
# It will call the 'gemini' CLI for each error reported in report.txt.
# BE AWARE: The '--yolo' flag means Gemini will attempt to fix issues autonomously.
# Review each command before execution if you are unsure.

