CREATE INDEX `agent_memories_agent_id_idx` ON `agent_memories` (`agent_id`);--> statement-breakpoint
CREATE INDEX `agent_memories_user_id_idx` ON `agent_memories` (`user_id`);--> statement-breakpoint
CREATE INDEX `agent_memories_conversation_id_idx` ON `agent_memories` (`conversation_id`);--> statement-breakpoint
CREATE INDEX `agent_memories_type_idx` ON `agent_memories` (`type`);--> statement-breakpoint
CREATE INDEX `agent_memories_importance_idx` ON `agent_memories` (`importance`);--> statement-breakpoint
CREATE INDEX `agent_memories_importance_score_idx` ON `agent_memories` (`importance_score`);--> statement-breakpoint
CREATE INDEX `agent_memories_access_count_idx` ON `agent_memories` (`access_count`);--> statement-breakpoint
CREATE INDEX `agent_memories_last_accessed_at_idx` ON `agent_memories` (`last_accessed_at`);--> statement-breakpoint
CREATE INDEX `agent_memories_is_archived_idx` ON `agent_memories` (`is_archived`);--> statement-breakpoint
CREATE INDEX `agent_memories_created_at_idx` ON `agent_memories` (`created_at`);--> statement-breakpoint
CREATE INDEX `agent_memories_agent_user_idx` ON `agent_memories` (`agent_id`,`user_id`);--> statement-breakpoint
CREATE INDEX `agent_memories_agent_type_idx` ON `agent_memories` (`agent_id`,`type`);--> statement-breakpoint
CREATE INDEX `agent_memories_agent_importance_idx` ON `agent_memories` (`agent_id`,`importance`);--> statement-breakpoint
CREATE INDEX `agent_memories_user_conversation_idx` ON `agent_memories` (`user_id`,`conversation_id`);--> statement-breakpoint
CREATE INDEX `memory_relations_source_memory_id_idx` ON `memory_relations` (`source_memory_id`);--> statement-breakpoint
CREATE INDEX `memory_relations_target_memory_id_idx` ON `memory_relations` (`target_memory_id`);--> statement-breakpoint
CREATE INDEX `memory_relations_relation_type_idx` ON `memory_relations` (`relation_type`);--> statement-breakpoint
CREATE INDEX `memory_relations_strength_idx` ON `memory_relations` (`strength`);--> statement-breakpoint
CREATE INDEX `memory_relations_source_relation_idx` ON `memory_relations` (`source_memory_id`,`relation_type`);--> statement-breakpoint
CREATE INDEX `memory_relations_target_relation_idx` ON `memory_relations` (`target_memory_id`,`relation_type`);--> statement-breakpoint
CREATE INDEX `conversation_participants_conversation_id_idx` ON `conversation_participants` (`conversation_id`);--> statement-breakpoint
CREATE INDEX `conversation_participants_participant_id_idx` ON `conversation_participants` (`participant_id`);--> statement-breakpoint
CREATE INDEX `conversation_participants_conversation_participant_idx` ON `conversation_participants` (`conversation_id`,`participant_id`);--> statement-breakpoint
CREATE INDEX `conversations_agent_id_idx` ON `conversations` (`agent_id`);--> statement-breakpoint
CREATE INDEX `conversations_type_idx` ON `conversations` (`type`);--> statement-breakpoint
CREATE INDEX `conversations_created_at_idx` ON `conversations` (`created_at`);--> statement-breakpoint
CREATE INDEX `llm_messages_message_id_idx` ON `llm_messages` (`message_id`);--> statement-breakpoint
CREATE INDEX `llm_messages_role_idx` ON `llm_messages` (`role`);--> statement-breakpoint
CREATE INDEX `llm_messages_created_at_idx` ON `llm_messages` (`created_at`);--> statement-breakpoint
CREATE INDEX `messages_conversation_id_idx` ON `messages` (`conversation_id`);--> statement-breakpoint
CREATE INDEX `messages_author_id_idx` ON `messages` (`author_id`);--> statement-breakpoint
CREATE INDEX `messages_created_at_idx` ON `messages` (`created_at`);--> statement-breakpoint
CREATE INDEX `messages_conversation_time_idx` ON `messages` (`conversation_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `user_preferences_user_id_idx` ON `user_preferences` (`user_id`);--> statement-breakpoint
CREATE INDEX `user_preferences_theme_idx` ON `user_preferences` (`theme`);