export interface Repository {
  name: string;
  url: string;
  status: "active" | "inactive";
  issues: number;
  prs: number;
  branches: number;
  lastSync: string; // ISO date string
}

export interface RepositorySettings {
  repoUrl: string;
  accessToken: string;
  autoCreatePR: boolean;
  autoGenerateDocs: boolean;
}

export type Token = string;