import { useState } from "react";
import { formatDate } from "../lib/utils";

export function useRepositorySettings() {
  const [repoUrl, setRepoUrl] = useState("");
  const [accessToken, setAccessToken] = useState("");
  const [autoCreatePR, setAutoCreatePR] = useState(false);
  const [autoGenerateDocs, setAutoGenerateDocs] = useState(false);

  // Example repositories data (mock)
  const repositories = [
    {
      name: "project-wiz",
      url: "https://github.com/user/project-wiz",
      status: "active",
      issues: 12,
      prs: 5,
      branches: 4,
      lastSync: "2023-06-15T14:30:00",
    },
    {
      name: "another-repo",
      url: "https://github.com/user/another-repo",
      status: "inactive",
      issues: 8,
      prs: 2,
      branches: 3,
      lastSync: "2023-06-13T11:20:00",
    },
  ];

  return {
    repoUrl,
    setRepoUrl,
    accessToken,
    setAccessToken,
    autoCreatePR,
    setAutoCreatePR,
    autoGenerateDocs,
    setAutoGenerateDocs,
    repositories,
    formatDate,
  };
}