/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as IndexImport } from './pages/index'
import { Route as SettingsIndexImport } from './pages/settings/index'
import { Route as RepositoriesIndexImport } from './pages/repositories/index'
import { Route as DocumentationIndexImport } from './pages/documentation/index'
import { Route as ActivityLogIndexImport } from './pages/activity-log/index'
import { Route as ModelsModelsPageImport } from './pages/models/models-page'
import { Route as RepositoriesPresentationRepositoriesPageImport } from './pages/repositories/presentation/RepositoriesPage'
import { Route as RepositoriesApplicationRepositoriesControllerImport } from './pages/repositories/application/RepositoriesController'
import { Route as RepositoriesInfrastructureRouterRepositoriesRouterImport } from './pages/repositories/infrastructure/router/repositories-router'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const RepositoriesIndexRoute = RepositoriesIndexImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRoute,
} as any)

const DocumentationIndexRoute = DocumentationIndexImport.update({
  id: '/documentation/',
  path: '/documentation/',
  getParentRoute: () => rootRoute,
} as any)

const ActivityLogIndexRoute = ActivityLogIndexImport.update({
  id: '/activity-log/',
  path: '/activity-log/',
  getParentRoute: () => rootRoute,
} as any)

const ModelsModelsPageRoute = ModelsModelsPageImport.update({
  id: '/models/models-page',
  path: '/models/models-page',
  getParentRoute: () => rootRoute,
} as any)

const RepositoriesPresentationRepositoriesPageRoute =
  RepositoriesPresentationRepositoriesPageImport.update({
    id: '/repositories/presentation/RepositoriesPage',
    path: '/repositories/presentation/RepositoriesPage',
    getParentRoute: () => rootRoute,
  } as any)

const RepositoriesApplicationRepositoriesControllerRoute =
  RepositoriesApplicationRepositoriesControllerImport.update({
    id: '/repositories/application/RepositoriesController',
    path: '/repositories/application/RepositoriesController',
    getParentRoute: () => rootRoute,
  } as any)

const RepositoriesInfrastructureRouterRepositoriesRouterRoute =
  RepositoriesInfrastructureRouterRepositoriesRouterImport.update({
    id: '/repositories/infrastructure/router/repositories-router',
    path: '/repositories/infrastructure/router/repositories-router',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/models/models-page': {
      id: '/models/models-page'
      path: '/models/models-page'
      fullPath: '/models/models-page'
      preLoaderRoute: typeof ModelsModelsPageImport
      parentRoute: typeof rootRoute
    }
    '/activity-log/': {
      id: '/activity-log/'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof ActivityLogIndexImport
      parentRoute: typeof rootRoute
    }
    '/documentation/': {
      id: '/documentation/'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationIndexImport
      parentRoute: typeof rootRoute
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/repositories/application/RepositoriesController': {
      id: '/repositories/application/RepositoriesController'
      path: '/repositories/application/RepositoriesController'
      fullPath: '/repositories/application/RepositoriesController'
      preLoaderRoute: typeof RepositoriesApplicationRepositoriesControllerImport
      parentRoute: typeof rootRoute
    }
    '/repositories/presentation/RepositoriesPage': {
      id: '/repositories/presentation/RepositoriesPage'
      path: '/repositories/presentation/RepositoriesPage'
      fullPath: '/repositories/presentation/RepositoriesPage'
      preLoaderRoute: typeof RepositoriesPresentationRepositoriesPageImport
      parentRoute: typeof rootRoute
    }
    '/repositories/infrastructure/router/repositories-router': {
      id: '/repositories/infrastructure/router/repositories-router'
      path: '/repositories/infrastructure/router/repositories-router'
      fullPath: '/repositories/infrastructure/router/repositories-router'
      preLoaderRoute: typeof RepositoriesInfrastructureRouterRepositoriesRouterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/models/models-page': typeof ModelsModelsPageRoute
  '/activity-log': typeof ActivityLogIndexRoute
  '/documentation': typeof DocumentationIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/repositories/application/RepositoriesController': typeof RepositoriesApplicationRepositoriesControllerRoute
  '/repositories/presentation/RepositoriesPage': typeof RepositoriesPresentationRepositoriesPageRoute
  '/repositories/infrastructure/router/repositories-router': typeof RepositoriesInfrastructureRouterRepositoriesRouterRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/models/models-page': typeof ModelsModelsPageRoute
  '/activity-log': typeof ActivityLogIndexRoute
  '/documentation': typeof DocumentationIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/repositories/application/RepositoriesController': typeof RepositoriesApplicationRepositoriesControllerRoute
  '/repositories/presentation/RepositoriesPage': typeof RepositoriesPresentationRepositoriesPageRoute
  '/repositories/infrastructure/router/repositories-router': typeof RepositoriesInfrastructureRouterRepositoriesRouterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/models/models-page': typeof ModelsModelsPageRoute
  '/activity-log/': typeof ActivityLogIndexRoute
  '/documentation/': typeof DocumentationIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/repositories/application/RepositoriesController': typeof RepositoriesApplicationRepositoriesControllerRoute
  '/repositories/presentation/RepositoriesPage': typeof RepositoriesPresentationRepositoriesPageRoute
  '/repositories/infrastructure/router/repositories-router': typeof RepositoriesInfrastructureRouterRepositoriesRouterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/models/models-page'
    | '/activity-log'
    | '/documentation'
    | '/repositories'
    | '/settings'
    | '/repositories/application/RepositoriesController'
    | '/repositories/presentation/RepositoriesPage'
    | '/repositories/infrastructure/router/repositories-router'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/models/models-page'
    | '/activity-log'
    | '/documentation'
    | '/repositories'
    | '/settings'
    | '/repositories/application/RepositoriesController'
    | '/repositories/presentation/RepositoriesPage'
    | '/repositories/infrastructure/router/repositories-router'
  id:
    | '__root__'
    | '/'
    | '/models/models-page'
    | '/activity-log/'
    | '/documentation/'
    | '/repositories/'
    | '/settings/'
    | '/repositories/application/RepositoriesController'
    | '/repositories/presentation/RepositoriesPage'
    | '/repositories/infrastructure/router/repositories-router'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelsModelsPageRoute: typeof ModelsModelsPageRoute
  ActivityLogIndexRoute: typeof ActivityLogIndexRoute
  DocumentationIndexRoute: typeof DocumentationIndexRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  RepositoriesApplicationRepositoriesControllerRoute: typeof RepositoriesApplicationRepositoriesControllerRoute
  RepositoriesPresentationRepositoriesPageRoute: typeof RepositoriesPresentationRepositoriesPageRoute
  RepositoriesInfrastructureRouterRepositoriesRouterRoute: typeof RepositoriesInfrastructureRouterRepositoriesRouterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelsModelsPageRoute: ModelsModelsPageRoute,
  ActivityLogIndexRoute: ActivityLogIndexRoute,
  DocumentationIndexRoute: DocumentationIndexRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  RepositoriesApplicationRepositoriesControllerRoute:
    RepositoriesApplicationRepositoriesControllerRoute,
  RepositoriesPresentationRepositoriesPageRoute:
    RepositoriesPresentationRepositoriesPageRoute,
  RepositoriesInfrastructureRouterRepositoriesRouterRoute:
    RepositoriesInfrastructureRouterRepositoriesRouterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/models/models-page",
        "/activity-log/",
        "/documentation/",
        "/repositories/",
        "/settings/",
        "/repositories/application/RepositoriesController",
        "/repositories/presentation/RepositoriesPage",
        "/repositories/infrastructure/router/repositories-router"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/models/models-page": {
      "filePath": "models/models-page.tsx"
    },
    "/activity-log/": {
      "filePath": "activity-log/index.tsx"
    },
    "/documentation/": {
      "filePath": "documentation/index.tsx"
    },
    "/repositories/": {
      "filePath": "repositories/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    },
    "/repositories/application/RepositoriesController": {
      "filePath": "repositories/application/RepositoriesController.tsx"
    },
    "/repositories/presentation/RepositoriesPage": {
      "filePath": "repositories/presentation/RepositoriesPage.tsx"
    },
    "/repositories/infrastructure/router/repositories-router": {
      "filePath": "repositories/infrastructure/router/repositories-router.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
